/**
 * palm.ts — Shared TypeScript types for PalmVerse
 *
 * WHY A SEPARATE TYPES FILE:
 *   TypeScript interfaces define the "shape" of data flowing through the app.
 *   Keeping them in one place means:
 *   - Any component can import exactly the type it needs
 *   - If the API response shape changes (e.g. when we replace the mock
 *     with a real FastAPI response), we only update this file
 *   - TypeScript will immediately flag any component using the old shape
 */

// ── User details collected in Step 1 ─────────────────────────────────────────
export interface UserDetails {
  name: string;
  dateOfBirth: string;      // ISO date string: "YYYY-MM-DD"
  placeOfBirth: string;
  gender?: "male" | "female" | "non-binary" | "prefer-not-to-say" | "";
}

// ── A single category in the palm reading ────────────────────────────────────
export interface ReadingCategory {
  score: number;            // 0–100
  summary: string;          // Short one-liner shown on the card
  details: string;          // Longer reading revealed on expand
  icon: string;             // Emoji icon
  label: string;            // Display name e.g. "Love & Relationships"
}

// ── The full palm reading result ─────────────────────────────────────────────
// FUTURE: This will be returned by FastAPI → CV pipeline → Interpretation Engine
// For now, it is generated by src/services/mockPalmAnalysis.ts
export interface PalmReadingResult {
  overallSummary: string;
  categories: {
    love:        ReadingCategory;
    career:      ReadingCategory;
    money:       ReadingCategory;
    wellbeing:   ReadingCategory;
    mind:        ReadingCategory;
    path:        ReadingCategory;
  };
  generatedAt: string;      // ISO timestamp
}

// ── Global application state ─────────────────────────────────────────────────
export interface PalmReadingState {
  // Step 1 — User details
  userDetails: UserDetails | null;

  // Step 2 — Captured palm image (stored as a data URL or object URL)
  palmImage: string | null;

  // Step 3 — Analysis result
  result: PalmReadingResult | null;

  // Whether the user has completed the full flow
  isComplete: boolean;
}
